import type { CreativeMapPoint, Hike, TravelPlace } from "../../types/content";

export const places: TravelPlace[] = [
  {
    slug: "point-reyes",
    title: "Point Reyes",
    location: "Marin County, California",
    country: "United States",
    kind: "nature",
    coordinates: [-122.851, 38.083],
    visited: "2025-07",
    summary:
      "Coastal trails, working ranches, fog, and long views across the Pacific.",
    relatedPhotoTripSlug: "pacific-coast-weekend",
    status: "placeholder",
  },
  {
    slug: "joshua-tree",
    title: "Joshua Tree",
    location: "Southern California",
    country: "United States",
    kind: "nature",
    coordinates: [-116.319, 33.873],
    visited: "2025-03",
    summary:
      "High desert terrain studied through granite forms, plant life, and changing light.",
    relatedPhotoTripSlug: "high-desert-spring",
    status: "placeholder",
  },
  {
    slug: "lake-tahoe",
    title: "Lake Tahoe",
    location: "California and Nevada",
    country: "United States",
    kind: "nature",
    coordinates: [-120.043, 38.939],
    visited: "2025-08",
    summary:
      "A high-elevation landscape connecting lake weather and long alpine routes.",
    relatedPhotoTripSlug: "tahoe-alpine-summer",
    relatedHikeSlug: "mount-tallac",
    status: "placeholder",
  },
  {
    slug: "yosemite-valley",
    title: "Yosemite Valley",
    location: "Sierra Nevada, California",
    country: "United States",
    kind: "landmark",
    coordinates: [-119.558, 37.733],
    visited: "2024-06",
    summary:
      "Granite walls, river corridors, and the changing scale of the valley on foot.",
    relatedHikeSlug: "mist-trail",
    status: "placeholder",
  },
  {
    slug: "iceland-south-coast",
    title: "Iceland South Coast",
    location: "Southern Region",
    country: "Iceland",
    kind: "nature",
    coordinates: [-19.02, 64.15],
    visited: "2024-09",
    summary:
      "A placeholder international record linking northern coastal weather to a complete photography folder.",
    relatedPhotoTripSlug: "iceland-south-coast",
    status: "placeholder",
  },
  {
    slug: "kyoto",
    title: "Kyoto",
    location: "Kansai",
    country: "Japan",
    kind: "city",
    coordinates: [135.768, 35.011],
    visited: "2024-05",
    summary:
      "A placeholder city record built around neighborhood scale, rain, gardens, and architectural detail.",
    relatedPhotoTripSlug: "kyoto-in-rain",
    status: "placeholder",
  },
  {
    slug: "torres-del-paine",
    title: "Torres del Paine",
    location: "Magallanes Region",
    country: "Chile",
    kind: "nature",
    coordinates: [-72.987, -50.942],
    visited: "2023-11",
    summary:
      "A placeholder southern landscape record for mountain weather, trail camps, and open steppe.",
    relatedPhotoTripSlug: "patagonia-wind",
    status: "placeholder",
  },
];

export const hikes: Hike[] = [
  {
    slug: "mount-tallac",
    trail: "Mount Tallac",
    location: "Lake Tahoe, California",
    country: "United States",
    date: "2025-08",
    coordinates: [-120.067, 38.921],
    distanceMiles: 10.2,
    elevationFeet: 3260,
    movingHours: 6.4,
    difficulty: "Strenuous",
    summary:
      "A sustained alpine climb with changing terrain and broad views over the Tahoe basin.",
    route: {
      points: [
        [-120.067, 38.921],
        [-120.073, 38.915],
        [-120.08, 38.909],
        [-120.085, 38.9],
        [-120.095, 38.893],
        [-120.102, 38.906],
      ],
      strava: {
        provider: "strava",
        title: "Mount Tallac route",
        placeholder: true,
      },
      placeholder: true,
    },
    relatedPhotoTripSlug: "tahoe-alpine-summer",
    status: "placeholder",
  },
  {
    slug: "mist-trail",
    trail: "Mist Trail",
    location: "Yosemite, California",
    country: "United States",
    date: "2024-06",
    coordinates: [-119.558, 37.733],
    distanceMiles: 7,
    elevationFeet: 2100,
    movingHours: 5.1,
    difficulty: "Strenuous",
    summary:
      "Granite steps, heavy water, and a close look at the valley's changing scale.",
    route: {
      points: [
        [-119.558, 37.733],
        [-119.552, 37.729],
        [-119.547, 37.725],
        [-119.538, 37.724],
        [-119.532, 37.728],
      ],
      strava: {
        provider: "strava",
        title: "Mist Trail activity",
        placeholder: true,
      },
      placeholder: true,
    },
    status: "placeholder",
  },
  {
    slug: "coast-trail",
    trail: "Coast Trail",
    location: "Point Reyes, California",
    country: "United States",
    date: "2024-03",
    coordinates: [-122.8, 38.04],
    distanceMiles: 8.6,
    elevationFeet: 1380,
    movingHours: 4.2,
    difficulty: "Moderate",
    summary:
      "A green-weather walk between eucalyptus shade, open bluffs, and the Pacific.",
    route: {
      points: [
        [-122.8, 38.04],
        [-122.806, 38.032],
        [-122.817, 38.024],
        [-122.826, 38.017],
        [-122.835, 38.01],
      ],
      strava: {
        provider: "strava",
        title: "Coast Trail activity",
        placeholder: true,
      },
      placeholder: true,
    },
    relatedPhotoTripSlug: "pacific-coast-weekend",
    status: "placeholder",
  },
];

export const creativeMapPoints: CreativeMapPoint[] = [
  {
    id: "map-photo-pacific-coast-weekend",
    label: "Pacific Coast Weekend photo folder",
    coordinates: [-122.851, 38.083],
    kind: "photography",
    to: "/creative/photography/pacific-coast-weekend",
  },
  {
    id: "map-photo-high-desert-spring",
    label: "High Desert in Spring photo folder",
    coordinates: [-116.319, 33.873],
    kind: "photography",
    to: "/creative/photography/high-desert-spring",
  },
  {
    id: "map-photo-tahoe-alpine-summer",
    label: "Tahoe Alpine Summer photo folder",
    coordinates: [-120.043, 38.939],
    kind: "photography",
    to: "/creative/photography/tahoe-alpine-summer",
  },
  {
    id: "map-photo-iceland-south-coast",
    label: "Iceland South Coast photo folder",
    coordinates: [-19.02, 64.15],
    kind: "photography",
    to: "/creative/photography/iceland-south-coast",
  },
  {
    id: "map-photo-kyoto-in-rain",
    label: "Kyoto in Rain photo folder",
    coordinates: [135.768, 35.011],
    kind: "photography",
    to: "/creative/photography/kyoto-in-rain",
  },
  {
    id: "map-photo-patagonia-wind",
    label: "Patagonia Wind photo folder",
    coordinates: [-72.987, -50.942],
    kind: "photography",
    to: "/creative/photography/patagonia-wind",
  },
  {
    id: "map-photo-mt-rainier-camping",
    label: "Mt. Rainier Camping photo folder",
    coordinates: [-121.761, 46.8528],
    kind: "photography",
    to: "/creative/photography/mt-rainier-camping",
  },
  {
    id: "map-hike-mount-tallac",
    label: "Mount Tallac hike",
    coordinates: [-120.067, 38.921],
    kind: "hike",
    to: "/creative/travel/hikes/mount-tallac",
  },
  {
    id: "map-hike-mist-trail",
    label: "Mist Trail hike",
    coordinates: [-119.558, 37.733],
    kind: "hike",
    to: "/creative/travel/hikes/mist-trail",
  },
  {
    id: "map-hike-coast-trail",
    label: "Coast Trail hike",
    coordinates: [-122.8, 38.04],
    kind: "hike",
    to: "/creative/travel/hikes/coast-trail",
  },
];
